"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, FileText, Lightbulb, Network } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { GlowCard } from "@/components/shared/GlowCard";

const containerVariants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } }
};

const cardVariants = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } }
};

const floatingCards = [
  {
    icon: FileText,
    title: "Executive Summary",
    body: "Three-sentence strategic frame with key thesis and decision signals."
  },
  {
    icon: Lightbulb,
    title: "Key Insights",
    body: "Ranked observations with impact scores and evidence references."
  },
  {
    icon: Network,
    title: "Concept Map",
    body: "Connected themes, entities, and actions with relationship clarity."
  }
];

export function Hero() {
  return (
    <section className="relative overflow-hidden bg-mesh-hero pb-24 pt-20 lg:pt-28">
      <div className="mx-auto grid w-full max-w-7xl gap-10 px-4 lg:grid-cols-[1.25fr_1fr] lg:px-8">
        <motion.div
          animate={{ opacity: 1, y: 0 }}
          initial={{ opacity: 0, y: 16 }}
          transition={{ duration: 0.45 }}
          className="space-y-8"
        >
          <div className="inline-flex rounded-full border border-cyan-400/30 bg-cyan-500/5 px-4 py-1 text-xs text-cyan-300">
            AI Executive Briefing Generator
          </div>
          <h1 className="max-w-3xl font-display text-5xl leading-[1.05] text-brand-text md:text-7xl">
            Turn 500 Pages Into 2 Minutes
          </h1>
          <p className="max-w-2xl text-lg text-brand-muted">
            BriefMind distills research papers, reports and documents into executive intelligence.
          </p>
          <div className="flex flex-wrap items-center gap-3">
            <Link href="/app">
              <Button className="animate-glow-pulse gap-2" size="lg">
                Start Briefing
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Dialog>
              <DialogTrigger asChild>
                <Button size="lg" variant="outline">See Example</Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Sample Briefing Snapshot</DialogTitle>
                  <DialogDescription>Condensed output style generated by BriefMind.</DialogDescription>
                </DialogHeader>
                <div className="space-y-4 text-sm text-brand-muted">
                  <p>
                    <span className="font-semibold text-brand-text">Headline:</span> Enterprise AI adoption is accelerating,
                    but governance readiness is the central execution bottleneck.
                  </p>
                  <p>
                    <span className="font-semibold text-brand-text">Core Message:</span> Prioritize a lightweight decision
                    framework before scaling pilots to avoid fragmented tooling and policy drift.
                  </p>
                  <p>
                    <span className="font-semibold text-brand-text">Bottom Line:</span> A 90-day governance sprint can reduce
                    rollout risk while preserving innovation velocity.
                  </p>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </motion.div>

        <motion.div
          className="grid gap-4"
          initial="hidden"
          variants={containerVariants}
          whileInView="visible"
          viewport={{ once: true, amount: 0.3 }}
        >
          {floatingCards.map((card, index) => (
            <motion.div
              key={card.title}
              variants={cardVariants}
              className="animate-float"
              style={{ animationDelay: `${index * 0.8}s` }}
            >
              <GlowCard className="glass-border bg-black/25">
                <div className="mb-3 flex items-center gap-2 text-cyan-300">
                  <card.icon className="h-4 w-4" />
                  <h3 className="font-display text-lg text-brand-text">{card.title}</h3>
                </div>
                <p className="text-sm text-brand-muted">{card.body}</p>
              </GlowCard>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}

